//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Todo
    {
        public System.Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        [StringLength(50)]
        public string Priority { get; set; }
        [StringLength(50)]
        public string Responsible { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
